# Generated by Django 2.2.5 on 2019-10-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmain', '0002_auto_20191003_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menustate',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menutype',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
