# Generated by Django 2.2.4 on 2019-10-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmain', '0003_auto_20191003_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
