# Generated by Django 2.2.5 on 2019-10-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsadmain', '0004_news_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
